### ISSUE TITLE
WSL2 browser issue

### ISSUE THREAD

**Issue by genmeblog** [eerohele/tab#1]
On WSL2 (Linux on Windows) nothing happens after running basic example, ie:

```
user=> (require 'tab.auto)
nil
user=> (tap> BigInteger)
true
```

The problem is with a `clojure.java.browse` on WSL (which calls `xdg-open`, which requires a browser installed by `snap` which requires `systemd` which is not or partly supported etc... :) ).

Anyway. It would be nice to see which port was choosen by `tab.auto` to be able to reach the page manually.

**Comment by eerohele** [comment]
Thanks for filing the issue! Yeah, `tab.auto` should probably print the address.

In the meantime, you can do this to tell Tab not to open the browser:

```clojure
(require '[tab.api :as tab])

(def tab (tab/run :port 1234 :browse? false))
```

You can use `tab.api/address` on `tab` to get the address where tab is running.

**Comment by eerohele** [comment]
Fixed in https://github.com/eerohele/tab/commit/158af3b99dab4180e9a19b069dd9f793f2594e62.

In general, though, you'll probably want to use `tab.api`, and the README maybe oughta emphasize that more.

**Comment by genmeblog** [comment]
Thanks!
